### PR TITLE
gh-46: add infrastructure for coveralls (coverage)

### PR DESCRIPTION
**Pull request by Saransh-cpp**
Add code coverage in workflow using pytest-cov and coveralls.

Closes: #46
Ref: #180

### CODE REVIEW

**Comment by ntessore** [comment]
Looking at the action, the coverage sees none of the lines run in `glass`?

(Also, the tests in `glass/core/test` are still in the source tree, but that's for another issue.)

**Comment by ntessore** [comment]
This is still installing `glass` in the `pip install` step, but gathering the coverage for the `glass` folder in the source tree.

**Comment by Saransh-cpp** [comment]
Works now! `pytest-cov` requires editable build/install. I will merge this after #217 is merged.

**Review by ntessore — APPROVED** [review]
Excellent!

**Pull request merged**
