### PR TITLE
gh-384: rename all internal functions to `trapezoid` over `trapz`

### LINKED ISSUE #384: Change all functions with `trapz` in the name to `trapezoid` in line with NumPy v2
### Is Your Feature Request Related to a Problem? Please Describe

As part of #163 we will have to change all uses of `np.trapz` to `np.trapezoid`, it would make sense to change the functions like `cumtrapz` to `cumtrapezoid` etc.

### Describe the Solution You'd Like

_No response_

### Describe Alternatives You've Considered

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by paddyroddy**
Closes #384. Blocked by #391.

Keeping in line with `NumPy v2` renaming `np.trap` to `np.trapezoid`. It was agreed to change the internal name of functions to avoid potential confusion.

### CODE REVIEW

**Review by Saransh-cpp — APPROVED** [review]
Ah, I forgot to approve, just commented by mistake

**Review by ntessore — COMMENTED** [review]
Maybe better to carry on agreeing with the scipy name, i.e., now `cumulative_trapezoid`?

**Comment by paddyroddy** [comment]
> Maybe better to carry on agreeing with the scipy name, i.e., now `cumulative_trapezoid`?

Sure. `cumtrapezoid` without the `_` does seem a bit ugly.

**Review by Saransh-cpp — CHANGES_REQUESTED** [review]
This, @paddyroddy! Could you fix the git history?

**Comment by paddyroddy** [comment]
> This, @paddyroddy! Could you fix the git history?

We're squash merging... I don't see the benefit

**Comment by paddyroddy** [comment]
> This, @paddyroddy! Could you fix the git history?

For reference, this happened because the head was #391. I do think tidying this is a waste of dev time with squash merging enabled.

**Review by Saransh-cpp — APPROVED** [review]
Fair enough, everything should be fine as long as the commit message of the squashed commit does not reflect this history.

**Review by ntessore — APPROVED** [review]
Nice, thanks!

I just realised that I thought we were testing the cumulative trapezoid by chopping the array down to 1, 2, 3, ... elements, not scipy. Maybe a change for the future to get rid of that dependency.

**Pull request merged**
