### PR TITLE
gh-257: use pytest-mock instead of unittest.mock

### PR DESCRIPTION
**Pull request by Saransh-cpp**
Replaces `unittest.mock.Mock` with pytest's mocking plugin - `pytest-mock` ( a new `tests` dependency now).

Closes: #257

### CODE REVIEW

**Review by paddyroddy — CHANGES_REQUESTED** [review]
Can you add some text to the PR body?

**Comment by ntessore** [comment]
Sorry, is there any benefit at all to this change? If not, why add a dependency that might stop working at any point?

**Comment by Saransh-cpp** [comment]
The benefit imo - using one testing framework uniformly across the project. [pytest-mock](https://github.com/pytest-dev/pytest-mock/) is maintained by pytest itself, so there are no chances of it breaking (techincally `pytest` is a third party library/dependency too, so you could argue that it might break sometime and we should use `unittest` for everything, but the `pytest` ecosystem is well tested and is used extensively within the Python ecosystem).

**Comment by ntessore** [comment]
> The benefit imo - using one testing framework uniformly across the project. [pytest-mock](https://github.com/pytest-dev/pytest-mock/) is maintained by pytest itself, so there are no chances of it breaking

Ah, excellent, I thought it was a third-party project. That makes sense!

**Review by paddyroddy — APPROVED** [review]

**Pull request merged**
