### PR TITLE
gh-163: full support of `NumPy v2`

### LINKED ISSUE #163: NumPy 2 compatibility (+ drop `3.9` support)
Ensure compatibility with the NumPy 2 release.

### LINKED ISSUE #189: Change dependencies to `~-` syntax rather than `>=`
My concern is for example `NumPy` now has v2 (#163), the current syntax would allow that when the code doesn't necessarily support it yet.

### PR DESCRIPTION
**Pull request by paddyroddy**
Fixes #163. Think the only change is required is `np.trapz` to `np.trapezoid`, verified with [NPY201](https://docs.astral.sh/ruff/rules/numpy2-deprecation). Also fixes #189.

### CODE REVIEW

**Comment by paddyroddy** [comment]
Have had to drop `3.8-3.9` support for full v2 support. Fixes #198.

**Review by Saransh-cpp — COMMENTED** [review]
Looks good! But should this be 2 PRs? Or at least should be 2 separate CHANGELOG notes (dropping Python versions should go in breaking changes?)?

**Comment by paddyroddy** [comment]
> Looks good! But should this be 2 PRs? Or at least should be 2 separate CHANGELOG notes (dropping Python versions should go in breaking changes?)?

Yeah I guess the Python changes (#198) should be done first, then NumPy. I hadn't realised they were necessary at the time.

**Comment by ntessore** [comment]
AFAICT, this would make numpy v2 _required_, not merely compatible without deprecations. I find that a bit of a strong requirement when the code works perfectly well with numpy<2 as well. Why not conditionally import `trapezoid` or `trapz as trapezoid` somewhere in our utility modules, then use that?

**Comment by paddyroddy** [comment]
> AFAICT, this would make numpy v2 _required_, not merely compatible without deprecations. I find that a bit of a strong requirement when the code works perfectly well with numpy<2 as well. Why not conditionally import `trapezoid` or `trapz as trapezoid` somewhere in our utility modules, then use that?

Yep, I had thought about that. I think this will become a piece of frustrating maintenance burden to be both API compatible, whilst still maintaining `numpy<2`. What do you think? Happy to do as you suggest, but I think it will quickly become a bit of a barrier

**Comment by ntessore** [comment]
I would probably keep it as long as it's one single change.

To be evaluated again if we start implementing the Array API, since NumPy 2 should be compatible with that out of the box, so we could forego the compatibility layer. Not sure if that's desirable, though, so probably something to discuss soon.

**Comment by paddyroddy** [comment]
> I would probably keep it as long as it's one single change.
> 
> To be evaluated again if we start implementing the Array API, since NumPy 2 should be compatible with that out of the box, so we could forego the compatibility layer. Not sure if that's desirable, though, so probably something to discuss soon.

Let's discuss this on Monday. Making sure I understand your POV.

**Comment by paddyroddy** [comment]
Closing in favour of #326. Can be revisited when we are happy to drop `3.9` support (#198).

**Pull request closed without merging**
