### PR TITLE
gh-173: don't bundle tests in SDist

### LINKED ISSUE #173: Move `test` folder outside the source distribution
Hotly debated topic, but fairly common practice https://docs.pytest.org/en/7.1.x/explanation/goodpractices.html#tests-outside-application-code

### PR DESCRIPTION
**Pull request by Saransh-cpp**
Fixes #173

Tests should not be bundled with SDist

Reviewed-by: Nicolas Tessore
Reviewed-by: Patrick J. Roddy <patrickjamesroddy@gmail.com>

### CODE REVIEW

**Review by paddyroddy — CHANGES_REQUESTED** [review]
It's probably better splitting this into separate PRs (sorry)

**Comment by paddyroddy** [comment]
I also dislike the huge `.gitignore` 😛 but appreciate, it's personal style

**Comment by Saransh-cpp** [comment]
Thanks! Removed the .gitignore. The update was prompted by a missing `.env` entry. No strong opinions on the file entries, maybe I can just include the environment folder in a different PR.

Edit: should the config update and the change of directory structure be 2 separate PRs as well?

**Review by ntessore — APPROVED** [review]

**Review by paddyroddy — APPROVED** [review]
Cheers!

**Pull request merged**
