### PR TITLE
gh-170: add scientific python recommended blacken-docs

### PR DESCRIPTION
**Pull request by Saransh-cpp**
Add blacken-docs for formatting of documentation files.

Refs: #170, #187

### CODE REVIEW

**Comment by ntessore** [comment]
Has this been run over the repository with no changes?

**Comment by Saransh-cpp** [comment]
Yes, everything is already in good shape.

**Review by paddyroddy — CHANGES_REQUESTED** [review]
Are you 100% sure this is not already covered by `ruff`?

**Review by paddyroddy — APPROVED** [review]

**Comment by paddyroddy** [comment]
> Are you 100% sure this is not already covered by `ruff`?

https://github.com/astral-sh/ruff/issues/3792

**Pull request merged**
